language: python
matrix:
  include:    # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pyinstaller copy_user_files.py
  - pyinstaller copy_user_files.spec
script:
  - pytest copy_user_files.py