language: python
matrix:
  include:
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
  - pip install pytest
before_script:
  - pyinstaller copy_user_files.py -y
  - pyinstaller copy_user_files.spec -y
script:
  - pytest copy_user_files.py -d _transfer -u travis